### ISSUE TITLE
How to create sample_data.json?

### ISSUE THREAD

**Issue by wmaucla** [anisha2102/docvqa#2]
Firstly thanks for making this open-source! I was looking through the example and was wondering how you get the `sample_data.json` file, as the DocVQA dataset task 1's ocr results .json files look very different. Thanks!

**Comment by anisha2102** [comment]
Hey,

Please check the [Prepare dataset](https://github.com/anisha2102/docvqa#prepare-dataset) section of the README. The `sample_data.json` is just a dummy sample of how the preprocessed data would look like. Due to restrictions on sharing the docvqa dataset as specified on their website, I have only hosted the code for preprocessing.

You can first get the dataset (train_v1.0.json and ocr trsnacripts) from the docvqa website and then continue to the preprocessing step. Hope this helps.
