### ISSUE TITLE
Using document chunks with no answer for training

### ISSUE THREAD

**Issue by nikoletta-toth** [anisha2102/docvqa#3]
Hi!

In the **utils_docvqa.py** script the **convert_examples_to_features** function is responsible for generating the features for training. I see you use a sliding window approach to cut documents that are longer than the maximum sequence length, so you end up doc parts with no answer in them. 

Why do you include those doc spans with no answer into the feature set at the end?
utils_docvqa.py line 308-327: here you state in the comment that you throw those docs out:
```
      if is_training and not example.is_impossible:
        # For training, if our document chunk does not contain an annotation
        # we throw it out, since there is nothing to predict.
```
but then you just set the start and end positions to 0, and include the feature into the final feature set. Is there a reason for that?
Why not just skip those examples and not include them into the feature set?

Thanks for the answer!

**Comment by anisha2102** [comment]
Hi, sorry for the misleading comment caused due to the adoption of parts of the code from the SQUAD training repository. 

Coming to your question about why did I include the chunks without the answer present in the training was due to:
1. Documents are generally quite large and they overshoot the 512 token limit for one inference call. This means that a single document may be split into 2-3 chunks and the answer will be present only in one of them. 
2. If the model is trained on such cases, it will learn to predict start and end positions as 0 when an answer is NOT present in the document chunk. This will in turn help reduce false predictions on test data where documents are split into multiple chunks.

That was the thought process for including them in the feature set. Hope this helps. Feel free to add your comments.

**Comment by nikoletta-toth** [comment]
Hi!

Thanks for the clarification, I got the same conclusion as your 2. point. 

If somebody is interested in it, I tested both versions of training, with and without the mentioned "doc chunks with no answer":
I trained the small model on the docVQA dataset without the annotated chunks, meaning that I set the loss in case of those chunks to 0, so the network doesn't learn anything from it. 
Then compared the results to the normal training without modifications: the accuracy on the val set and the learning curves during training are quite similar, there is no significant difference. I guess we would see a bigger difference if there was more label in the data set with no annotated answer.
